-- MySQL Script generated by MySQL Workbench
-- Mon May 25 00:32:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Task
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Task
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Task` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `Task` ;

-- -----------------------------------------------------
-- Table `Task`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `middle_name` VARCHAR(100) NULL DEFAULT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `location` VARCHAR(100) NULL DEFAULT NULL,
  `subscription_level` ENUM('basic', 'medium', 'premium') NULL DEFAULT 'basic',
  `subscription_expires` DATETIME NULL DEFAULT NULL,
  `task_limit` INT NULL DEFAULT '5',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`activity_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`activity_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `action` VARCHAR(100) NOT NULL,
  `target_type` VARCHAR(50) NULL DEFAULT NULL,
  `target_id` INT NULL DEFAULT NULL,
  `details` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_al_user_created_at` (`user_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_al_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `role` VARCHAR(50) NULL DEFAULT 'admin',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`blacklisted_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`blacklisted_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token_hash` CHAR(64) NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `reason` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_hash` (`token_hash` ASC) VISIBLE,
  INDEX `fk_blt_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blt_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`corrections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`corrections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `target_type` VARCHAR(50) NULL DEFAULT NULL,
  `target_id` INT NULL DEFAULT NULL,
  `correction_text` TEXT NULL DEFAULT NULL,
  `is_approved` TINYINT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_corr_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_corr_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `level` ENUM('debug', 'info', 'warn', 'error') NULL DEFAULT 'info',
  `message` TEXT NOT NULL,
  `context` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_logs_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`todos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `completed` TINYINT NULL DEFAULT '0',
  `difficulty` ENUM('easy', 'medium', 'hard') NULL DEFAULT 'easy',
  `parent_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT 'New',
  `due_date` DATETIME NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_todos_parent` (`parent_id` ASC) VISIBLE,
  INDEX `idx_todos_user_id_created_at` (`user_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_todos_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `Task`.`todos` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_todos_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type` ENUM('assignment', 'status_change', 'new_comment', 'role_change') NOT NULL,
  `message` TEXT NOT NULL,
  `related_task_id` INT NULL DEFAULT NULL,
  `is_read` TINYINT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_notif_related_task` (`related_task_id` ASC) VISIBLE,
  INDEX `idx_notif_user_created_at` (`user_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_notif_related_task`
    FOREIGN KEY (`related_task_id`)
    REFERENCES `Task`.`todos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_notif_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`task_collaborations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`task_collaborations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `type` ENUM('comment', 'code_snippet', 'math_solution', 'edit') NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tc_author` (`author_id` ASC) VISIBLE,
  INDEX `idx_tc_task_id_created_at` (`task_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_tc_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `Task`.`users` (`id`),
  CONSTRAINT `fk_tc_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `Task`.`todos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`task_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`task_participants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role` ENUM('Responsible', 'Observer', 'Co-executor', 'Manager') NULL DEFAULT 'Observer',
  `assigned_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_task_user` (`task_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `fk_tp_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_tp_task_id_user_id` (`task_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `Task`.`todos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tp_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Task`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `completed` TINYINT NULL DEFAULT '0',
  `difficulty` ENUM('easy', 'medium', 'hard') NULL DEFAULT 'easy',
  `status` VARCHAR(50) NULL DEFAULT 'New',
  `due_date` DATETIME NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Task`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
